version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    pull_policy: build
    ports:
      - 3856:5432
  web:
    build: .
    pull_policy: build
    depends_on:
      - db
    environment:
      GITHUB_RECIPES_READ_PAT_TOKEN: ${GITHUB_RECIPES_READ_PAT_TOKEN}
      GITHUB_RECIPES_WRITE_PAT_TOKEN: ${GITHUB_RECIPES_WRITE_PAT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PASSWORD: ${PASSWORD}
      SECRET: ${SECRET}
      IMGUR_ALBUM_ID: ${IMGUR_ALBUM_ID}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
      IMGUR_CLIENT_SECRET: ${IMGUR_CLIENT_SECRET}
      IMGUR_REFRESH_TOKEN: ${IMGUR_REFRESH_TOKEN}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chef-web.rule=Host(`chef.dennishilhorst.nl`)"
      - "traefik.http.routers.chef-web.entrypoints=websecure"
      - "traefik.http.routers.chef-web.tls.certresolver=myresolver"
      - "traefik.http.services.chef-web.loadbalancer.server.port=5000"
volumes:
  dbdata: