version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    depends_on:
      - db
    environment:
      GITHUB_RECIPES_READ_PAT_TOKEN: ${GITHUB_RECIPES_READ_PAT_TOKEN}
      GITHUB_RECIPES_WRITE_PAT_TOKEN: ${GITHUB_RECIPES_WRITE_PAT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PASSWORD: ${PASSWORD}
      SECRET: ${SECRET}
      IMGUR_ALBUM_ID: ${IMGUR_ALBUM_ID}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
      IMGUR_CLIENT_SECRET: ${IMGUR_CLIENT_SECRET}
      IMGUR_REFRESH_TOKEN: ${IMGUR_REFRESH_TOKEN}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 5000
    ports:
      - '80:5000'
volumes:
  dbdata: