version: '3.8'
services:
  web:
    build: .
    environment:
      GITHUB_RECIPES_READ_PAT_TOKEN: ${GITHUB_RECIPES_READ_PAT_TOKEN}
      GITHUB_RECIPES_WRITE_PAT_TOKEN: ${GITHUB_RECIPES_WRITE_PAT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PASSWORD: ${PASSWORD}
      SECRET: ${SECRET}
      IMGUR_ALBUM_ID: ${IMGUR_ALBUM_ID}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
      IMGUR_CLIENT_SECRET: ${IMGUR_CLIENT_SECRET}
      IMGUR_REFRESH_TOKEN: ${IMGUR_REFRESH_TOKEN}
      PORT: 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drlingo-web.rule=Host(`chef2.dennishilhorst.nl`)"
      - "traefik.http.routers.drlingo-web.entrypoints=websecure"
      - "traefik.http.routers.drlingo-web.tls.certresolver=myresolver"
      - "traefik.http.services.drlingo-web.loadbalancer.server.port=5000"